[package]
name = "EdgeCase"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
dotenv = "0.15"
tokio = { version = "1.36.0", features = ["full"] }
rand = "0.9.1"